### ISSUE TITLE
Crash on Mac starting missions with certain sounds

### ISSUE THREAD

**Issue by chief1983** [scp-fs2open/fs2open.github.com#1059]
Retail data, tried to start Massive Battle 2, CTD every time on the latest nightly (c930d1a, 10/24).  Crash to desktop, with what looks like an overflow of some sort.  Happens with a build I built from the same hash on Xcode 8.0 as well.  Seems related to the ffmpeg/avutil for sound stuff.

```
Process:               fs2_open_3_7_5_20161024_c930d1a_x64-FASTDBG [12550]
Path:                  /Applications/Freespace2/fs2_open_3_7_5_20161024_c930d1a_x64-FASTDBG.app/Contents/MacOS/fs2_open_3_7_5_20161024_c930d1a_x64-FASTDBG
Identifier:            fs2_open_3_7_5_20161024_c930d1a_x64-FASTDBG
Version:               FreeSpace 2 Open version 3.7.3 (???)
Code Type:             X86-64 (Native)
Parent Process:        wxlauncher [12498]
Responsible:           fs2_open_3_7_5_20161024_c930d1a_x64-FASTDBG [12550]
User ID:               501

Date/Time:             2016-10-28 11:50:31.767 -0500
OS Version:            Mac OS X 10.12.1 (16B2555)
Report Version:        12
Anonymous UUID:        472CFA93-DE50-E089-5209-AEC45F3F115A

Sleep/Wake UUID:       FB7875B6-3C22-4ED8-90B3-BD31C6FFB483

Time Awake Since Boot: 58000 seconds
Time Since Wake:       350 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
*** error for object 0x7fd6e2907200: pointer being freed was not allocated


Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib          0x00007fffc7decdda __pthread_kill + 10
1   libsystem_pthread.dylib         0x00007fffc7ed8787 pthread_kill + 90
2   libsystem_c.dylib               0x00007fffc7d52420 abort + 129
3   libsystem_malloc.dylib          0x00007fffc7e42097 free + 530
4   libavutil.55.30.100.dylib       0x0000000108b7460d av_buffer_unref + 61
5   fs2_open_3_7_5_20161024_c930d1a_x64-FASTDBG 0x00000001064df1cd snd_load(game_snd*, int) + 445
6   fs2_open_3_7_5_20161024_c930d1a_x64-FASTDBG 0x00000001060ee4e3 gamesnd_load_gameplay_sounds() + 195
7   fs2_open_3_7_5_20161024_c930d1a_x64-FASTDBG 0x0000000106030f43 freespace_mission_load_stuff() + 131
8   fs2_open_3_7_5_20161024_c930d1a_x64-FASTDBG 0x0000000106031078 game_post_level_init() + 184
9   fs2_open_3_7_5_20161024_c930d1a_x64-FASTDBG 0x0000000106031485 game_start_mission() + 437
10  fs2_open_3_7_5_20161024_c930d1a_x64-FASTDBG 0x000000010603edbb game_enter_state(int, int) + 683
11  fs2_open_3_7_5_20161024_c930d1a_x64-FASTDBG 0x00000001060ea796 gameseq_set_state(int, int) + 326
12  fs2_open_3_7_5_20161024_c930d1a_x64-FASTDBG 0x000000010603d7be game_process_event(int, int) + 286
13  fs2_open_3_7_5_20161024_c930d1a_x64-FASTDBG 0x00000001060eab8d gameseq_process_events() + 157
14  fs2_open_3_7_5_20161024_c930d1a_x64-FASTDBG 0x0000000106041089 game_main(int, char**) + 473
15  fs2_open_3_7_5_20161024_c930d1a_x64-FASTDBG 0x000000010604289a actual_main(int, char**) + 522
16  fs2_open_3_7_5_20161024_c930d1a_x64-FASTDBG 0x0000000106042ae2 main + 34
17  libdyld.dylib                   0x00007fffc7cbe255 start + 1
```

100% reproducible, so I omitted the rest of the report as it's probably not any use.

**Comment by chief1983** [comment]
```
==========================================================================
DEBUG SPEW: No debug_filter.cfg found, so only general, error, and warning
categories can be shown and no debug_filter.cfg info will be saved.
==========================================================================
  Initializing SDL...
FreeSpace 2 Open version: 3.7.5.20161024
Passed cmdline options:
  -missile_lighting
  -soft_particles
  -post_process
  -fxaa
  -fb_explosions
  -fb_thrusters
  -enable_shadows
  -no_deferred
  -no_vsync
  -ballistic_gauge
  -dualscanlines
  -rearm_timer
  -targetinfo
  -3dwarp
  -snd_preload
  -window
Building file index...
Found root pack '/Applications/Freespace2/FS2OGGcutscenepack.vp' with a checksum of 0x84396e99
Found root pack '/Applications/Freespace2/multi-mission-pack.vp' with a checksum of 0x377695e0
Found root pack '/Applications/Freespace2/multi-voice-pack.vp' with a checksum of 0xd50e7442
Found root pack '/Applications/Freespace2/root_fs2.vp' with a checksum of 0xce10d76c
Found root pack '/Applications/Freespace2/smarty_fs2.vp' with a checksum of 0xddeb3b1e
Found root pack '/Applications/Freespace2/sparky_fs2.vp' with a checksum of 0x164fe65a
Found root pack '/Applications/Freespace2/sparky_hi_fs2.vp' with a checksum of 0xa11d56f1
Found root pack '/Applications/Freespace2/stu_fs2.vp' with a checksum of 0xd77da83a
Found root pack '/Applications/Freespace2/tango1_fs2.vp' with a checksum of 0x4c25221e
Found root pack '/Applications/Freespace2/tango2_fs2.vp' with a checksum of 0x86920b82
Found root pack '/Applications/Freespace2/tango3_fs2.vp' with a checksum of 0x705e8d71
Found root pack '/Applications/Freespace2/warble_fs2.vp' with a checksum of 0xd85c305d
Searching root '/Users/cliffgordon/Library/Application Support/HardLightProductions/FreeSpaceOpen/' ... 1 files
Searching root '/Applications/Freespace2/' ... 0 files
Searching root pack '/Applications/Freespace2/FS2OGGcutscenepack.vp' ... 10 files
Searching root pack '/Applications/Freespace2/multi-mission-pack.vp' ... 110 files
Searching root pack '/Applications/Freespace2/multi-voice-pack.vp' ... 307 files
Searching root pack '/Applications/Freespace2/root_fs2.vp' ... 157 files
Searching root pack '/Applications/Freespace2/smarty_fs2.vp' ... 10 files
Searching root pack '/Applications/Freespace2/sparky_fs2.vp' ... 3027 files
Searching root pack '/Applications/Freespace2/sparky_hi_fs2.vp' ... 1337 files
Searching root pack '/Applications/Freespace2/stu_fs2.vp' ... 2355 files
Searching root pack '/Applications/Freespace2/tango1_fs2.vp' ... 32 files
Searching root pack '/Applications/Freespace2/tango2_fs2.vp' ... 15 files
Searching root pack '/Applications/Freespace2/tango3_fs2.vp' ... 10 files
Searching root pack '/Applications/Freespace2/warble_fs2.vp' ... 52 files
Found 14 roots and 7423 files.
AutoLang: Language auto-detection successful...
Setting language to English
Game Settings Table: Using Standard Loops For SEXP Arguments
Game Settings Table: Using standard event chaining behavior
Game Settings Table: External shaders are DISABLED
Initializing OpenAL...
  OpenAL Vendor     : Apple Computer Inc.
  OpenAL Renderer   : Software
  OpenAL Version    : 1.1

  Found extension "AL_EXT_float32".
You are not using OpenAL Soft. Disabling enhanced sound.

  Sample rate: 0 (44100)
  EFX enabled: NO
  Playback device: Built-in Output
  Capture device: Built-in Microphone
... OpenAL successfully initialized!
Failed to init speech
  Initializing SDL video...
Initializing OpenGL graphics device at 1024x768 with 32-bit color...
  Requested SDL Pixel values = R: 8, G: 8, B: 8, depth: 24, stencil: 8, double-buffer: 1, FSAA: 0
  Requested SDL Pixel values = R: 8, G: 8, B: 8, depth: 24, stencil: 8, double-buffer: 1, FSAA: 0
  Actual SDL Video values    = R: 8, G: 8, B: 8, depth: 24, stencil: 8, double-buffer: 1, FSAA: 0
  OpenGL Vendor    : Intel Inc.
  OpenGL Renderer  : Intel Iris Pro OpenGL Engine
  OpenGL Version   : 4.1 INTEL-10.20.23

Compiling new shader:
	Particle Effects
   Loading built-in default shader for: effect-v.sdr
   Loading built-in default shader for: effect-particle-f.sdr
Shader Variant Features:
Compiling new shader:
	Particle Effects
   Loading built-in default shader for: effect-v.sdr
   Loading built-in default shader for: effect-particle-f.sdr
   Loading built-in default shader for: effect-screen-g.sdr
Shader Variant Features:
	Geometry shader point-based particles
Compiling new shader:
	Distortion Effects
   Loading built-in default shader for: effect-distort-v.sdr
   Loading built-in default shader for: effect-distort-f.sdr
Shader Variant Features:
Compiling new shader:
	Shield Decals
   Loading built-in default shader for: shield-impact-v.sdr
   Loading built-in default shader for: shield-impact-f.sdr
Shader Variant Features:
Compiling new shader:
	Deferred Lighting
   Loading built-in default shader for: deferred-v.sdr
   Loading built-in default shader for: deferred-f.sdr
WARNING: Failed to find uniform 'specFactor'.
Shader Variant Features:
Compiling new shader:
	Clear Deferred Lighting Buffer
   Loading built-in default shader for: deferred-clear-v.sdr
   Loading built-in default shader for: deferred-clear-f.sdr
Shader Variant Features:
Compiling passthrough shader...
Compiling new shader:
	Passthrough
   Loading built-in default shader for: passthrough-v.sdr
   Loading built-in default shader for: passthrough-f.sdr
Shader Variant Features:

Compiling passthrough shader...
Compiling new shader:
	Post Processing
   Loading built-in default shader for: post-v.sdr
   Loading built-in default shader for: post-f.sdr
WARNING: Failed to find uniform 'depth_tex'.
WARNING: Failed to find uniform 'timer'.
Shader Variant Features:
Compiling new shader:
	Bloom Brightpass
   Loading built-in default shader for: post-v.sdr
   Loading built-in default shader for: brightpass-f.sdr
Shader Variant Features:
Compiling new shader:
	Gaussian Blur
   Loading built-in default shader for: post-v.sdr
   Loading built-in default shader for: blur-f.sdr
WARNING: Failed to find uniform 'debug'.
Shader Variant Features:
	Horizontal blur pass
Compiling new shader:
	Gaussian Blur
   Loading built-in default shader for: post-v.sdr
   Loading built-in default shader for: blur-f.sdr
WARNING: Failed to find uniform 'debug'.
Shader Variant Features:
	Vertical blur pass
Compiling new shader:
	Bloom Compositing
   Loading built-in default shader for: post-v.sdr
   Loading built-in default shader for: bloom-comp-f.sdr
Shader Variant Features:
Compiling new shader:
	FXAA
   Loading built-in default shader for: fxaa-v.sdr
   Loading built-in default shader for: fxaa-f.sdr
Shader Variant Features:
Compiling new shader:
	FXAA Prepass
   Loading built-in default shader for: post-v.sdr
   Loading built-in default shader for: fxaapre-f.sdr
Shader Variant Features:
  Max texture units: 2 (16)
  Max client texture states: 2 (1)
  Max elements vertices: 1048575
  Max elements indices: 150000
  Max texture size: 16384x16384
  Max render buffer size: 16384x16384
  Can use compressed textures: YES
  Texture compression available: YES
  Post-processing enabled: YES
  Using trilinear texture filter.
  OpenGL Shader Version: 4.10
... OpenGL init is complete!
Initializing path renderer...
Size of bitmap info = 1039 KB
Size of bitmap extra info = 64 bytes
ANI cursorweb with size 24x24 (25.0% wasted)
ANI cursorweb.ani with size 24x24 (25.0% wasted)
GRAPHICS: Initializing default colors...
SCRIPTING: Beginning initialization sequence...
SCRIPTING: Beginning Lua initialization...
LUA: Opening LUA state...
LUA: Initializing base Lua libraries...
LUA: Beginning ADE initialization
ADE: Initializing enumeration constants...
ADE: Assigning Lua session...
SCRIPTING: Beginning main hook parse sequence....
Wokka!  Error opening file (scripting.tbl)!
TABLES: Unable to parse 'scripting.tbl'!  Error message = Failed to open file.
SCRIPTING: Inititialization complete.
SCRIPTING: Splash screen overrides checked
SCRIPTING: Splash hook has been run
SCRIPTING: Splash screen conditional hook has been run
Using high memory settings...
Wokka!  Error opening file (interface.tbl)!
WMCGUI: Unable to parse 'interface.tbl'!  Error message = Failed to open file.
Dutifully converting retail sound 36, 'l_hit.wav' to a 3D sound...
Dutifully converting retail sound 37, 'm_hit.wav' to a 3D sound...
CFILE: Creating new directory '/Users/cliffgordon/Library/Application Support/HardLightProductions/FreeSpaceOpen/data/'
CFILE: Creating new directory '/Users/cliffgordon/Library/Application Support/HardLightProductions/FreeSpaceOpen/data/'
Initializing Joystick...
  No joysticks found
Printing joystick info:
  No joystick is being used.
Current soundtrack set to -1 in event_music_reset_choices
Wokka!  Error opening file (armor.tbl)!
TABLES: Unable to parse 'armor.tbl'!  Error message = Failed to open file.
ANI support1 with size 108x24 (25.0% wasted)
ANI damage1 with size 148x25 (21.9% wasted)
ANI wingman1 with size 71x53 (17.2% wasted)
ANI wingman2 with size 35x53 (17.2% wasted)
ANI wingman3 with size 14x53 (17.2% wasted)
ANI toggle1 with size 57x20 (37.5% wasted)
ANI head1 with size 164x132 (48.4% wasted)
ANI weapons1 with size 126x20 (37.5% wasted)
ANI objective1 with size 149x21 (34.4% wasted)
ANI netlag1 with size 29x30 (6.2% wasted)
ANI targhit1 with size 31x21 (34.4% wasted)
ANI time1 with size 47x23 (28.1% wasted)
ANI targetview1 with size 137x156 (39.1% wasted)
ANI targetview2 with size 4x96 (25.0% wasted)
ANI targetview3 with size 7x20 (37.5% wasted)
ANI 2_energy2 with size 86x96 (25.0% wasted)
ANI 2_reticle1 with size 40x24 (25.0% wasted)
ANI 2_leftarc with size 103x252 (1.6% wasted)
ANI 2_rightarc1 with size 103x252 (1.6% wasted)
ANI 2_toparc2 with size 35x24 (25.0% wasted)
ANI 2_toparc3 with size 41x29 (9.4% wasted)
ANI 2_lead1 with size 26x26 (18.8% wasted)
ANI 2_lock1 with size 56x53 (17.2% wasted)
ANI 2_lockspin with size 100x100 (21.9% wasted)
ANI energy1 with size 12x41 (35.9% wasted)
ANI 2_radar1 with size 209x170 (33.6% wasted)
TABLES => Starting parse of 'ssm.tbl'...
ANI cursor with size 24x24 (25.0% wasted)
ANI cursor.ani with size 24x24 (25.0% wasted)
FFmpeg library initialized!
FFmpeg: License: LGPL version 2.1 or later
Ships.tbl is : VALID
Weapons.tbl is : VALID
cfile_init() took 71
Initializing head tracking...
  No supported provider found, headtracking will be disabled...
Headtracking is not enabled...
Creating player for movie 'intro.mve'.
FFMPEG Log: [theora @ 0x7fd6e2912600] 7 bits left in packet 82
FFMPEG Log: [ogg @ 0x7fd6e28ffa00] Broken file, keyframe not correctly marked.
FFMPEG Log: [theora @ 0x7fd6e30e5c00] 7 bits left in packet 82
FFmpeg: Using video codec Theora (theora).
FFmpeg: Using audio codec Vorbis (vorbis).
Compiling new shader:
	Video Playback
   Loading built-in default shader for: video-v.sdr
   Loading built-in default shader for: video-f.sdr
Shader Variant Features:
FFMPEG Log: [ogg @ 0x7fd6e28ffa00] Broken file, keyframe not correctly marked.
FFMPEG Log: [ogg @ 0x7fd6e28ffa00] Broken file, keyframe not correctly marked.
Got event GS_EVENT_GAME_INIT (49) in state NOT A VALID STATE (0)
PLR => Loading 'chief1983.plr' with version 2...
PLR => Parsing:  Flags...
PLR => Parsing:  Info...
PLR => Parsing:  Scoring...
PLR => Parsing:  ScoringMulti...
PLR => Parsing:  HUD...
PLR => Parsing:  Variables...
PLR => Parsing:  Multiplayer...
PLR => Parsing:  Controls...
PLR => Parsing:  Settings...
PLR => Loading complete!
PLR => Verifying 'chief1983.plr' with version 2...
PLR => Parsing:  Flags...
PLR => Parsing:  Info...
PLR => Verifying complete!
PLR => Verifying 'chief1983.plr' with version 2...
PLR => Parsing:  Flags...
PLR => Parsing:  Info...
PLR => Verifying complete!
Got event GS_EVENT_MAIN_MENU (0) in state GS_STATE_INITIAL_PLAYER_SELECT (37)
PLR => Loading 'chief1983.plr' with version 2...
PLR => Parsing:  Flags...
PLR => Parsing:  Info...
PLR => Parsing:  Scoring...
PLR => Parsing:  ScoringMulti...
PLR => Parsing:  HUD...
PLR => Parsing:  Variables...
PLR => Parsing:  Multiplayer...
PLR => Parsing:  Controls...
PLR => Parsing:  Settings...
PLR => Loading complete!
CSG => Loading 'chief1983.FreeSpace2.csg' with version 5...
CSG => Parsing:  Flags...
CSG => Parsing:  Info...
CSG => Parsing:  Missions...
CSG => Parsing:  Techroom...
CSG => Parsing:  Loadout...
CSG => Parsing:  Scoring...
CSG => Parsing:  RedAlert...
CSG => Parsing:  HUD...
CSG => Parsing:  Variables...
CSG => Parsing:  Settings...
CSG => Parsing:  Controls...
CSG => Parsing:  Cutscenes...
CSG => Parsing:  Last Missions...
CSG => Loading complete!
CSG => Loading 'chief1983.FreeSpace2.csg' with version 5...
CSG => Parsing:  Flags...
CSG => Parsing:  Info...
CSG => Parsing:  Missions...
CSG => Parsing:  Techroom...
CSG => Parsing:  Loadout...
CSG => Parsing:  Scoring...
CSG => Parsing:  RedAlert...
CSG => Parsing:  HUD...
CSG => Parsing:  Variables...
CSG => Parsing:  Settings...
CSG => Parsing:  Controls...
CSG => Parsing:  Cutscenes...
CSG => Parsing:  Last Missions...
CSG => Loading complete!
ANI 2_mainwalk.ani with size 209x477 (6.8% wasted)
ANI 2_mainflyby.ani with size 509x189 (26.2% wasted)
ANI 2_maincrane.ani with size 192x116 (9.4% wasted)
ANI 2_mainexit.ani with size 319x174 (32.0% wasted)
ANI 2_mainbarracks.ani with size 273x158 (38.3% wasted)
ANI 2_mainreadyroom.ani with size 231x145 (43.4% wasted)
ANI 2_maintechroom.ani with size 69x119 (7.0% wasted)
ANI 2_mainoptions.ani with size 337x206 (19.5% wasted)
ANI 2_maincampaign.ani with size 308x190 (25.8% wasted)
Got event GS_EVENT_TECH_MENU (11) in state GS_STATE_MAIN_MENU (1)
Techroom successfully initialized, now changing tab...
Loading model 'fighter01.pof' into slot '0'
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
   Loading built-in default shader for: main-g.sdr
WARNING: Failed to find uniform 'modelMatrix'.
WARNING: Failed to find uniform 'viewMatrix'.
WARNING: Failed to find uniform 'projMatrix'.
WARNING: Failed to find uniform 'color'.
Shader Variant Features:
	Shadow Mapping
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Diffuse Mapping
	Animated Effects
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Fog Effect
	Diffuse Mapping
	Animated Effects
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Diffuse Mapping
	Deferred lighting
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Fog Effect
	Diffuse Mapping
	Deferred lighting
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Diffuse Mapping
	Animated Effects
	Submodel Transforms
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Fog Effect
	Diffuse Mapping
	Animated Effects
	Submodel Transforms
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Diffuse Mapping
	Submodel Transforms
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Fog Effect
	Diffuse Mapping
	Submodel Transforms
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Diffuse Mapping
	Animated Effects
	Deferred lighting
	Submodel Transforms
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Fog Effect
	Diffuse Mapping
	Animated Effects
	Deferred lighting
	Submodel Transforms
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Diffuse Mapping
	Deferred lighting
	Submodel Transforms
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Fog Effect
	Diffuse Mapping
	Deferred lighting
	Submodel Transforms
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Animated Effects
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Fog Effect
	Animated Effects
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Deferred lighting
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Fog Effect
	Deferred lighting
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Animated Effects
	Submodel Transforms
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Fog Effect
	Animated Effects
	Submodel Transforms
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Submodel Transforms
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Fog Effect
	Submodel Transforms
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Animated Effects
	Deferred lighting
	Submodel Transforms
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Fog Effect
	Animated Effects
	Deferred lighting
	Submodel Transforms
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Deferred lighting
	Submodel Transforms
	Clip Plane
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Fog Effect
	Deferred lighting
	Submodel Transforms
	Clip Plane
Submodel 'fighter01d-hull' is detail level 1 of 'fighter01c-hull'
Submodel 'fighter01c-hull' is detail level 1 of 'fighter01b-hull'
Submodel 'fighter01d-hull' is detail level 2 of 'fighter01b-hull'
Submodel 'fighter01c-hull' is detail level 2 of 'fighter01a-hull'
Submodel 'fighter01b-hull' is detail level 1 of 'fighter01a-hull'
Submodel 'fighter01d-hull' is detail level 3 of 'fighter01a-hull'
Submodel 'thruster01c' is detail level 2 of 'thruster01a'
Submodel 'thruster01b' is detail level 1 of 'thruster01a'
Submodel 'thruster02c' is detail level 2 of 'thruster02a'
Submodel 'thruster02b' is detail level 1 of 'thruster02a'
Frame  0 too long!!: frametime = 0.256 (0.256)
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
   Loading built-in default shader for: main-g.sdr
WARNING: Failed to find uniform 'modelMatrix'.
WARNING: Failed to find uniform 'viewMatrix'.
WARNING: Failed to find uniform 'projMatrix'.
WARNING: Failed to find uniform 'color'.
Shader Variant Features:
	Shadow Mapping
	Submodel Transforms
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
WARNING: Failed to find uniform 'viewMatrix'.
Shader Variant Features:
	Lighting
	Diffuse Mapping
	Shadows
	Submodel Transforms
Got event GS_EVENT_SIMULATOR_ROOM (58) in state GS_STATE_TECH_MENU (7)
Freeing all existing models...
Unloading model 'fighter01.pof' from slot '0'
CSG => Loading 'chief1983.FreeSpace2.csg' with version 5...
CSG => Parsing:  Flags...
CSG => Parsing:  Info...
CSG => Parsing:  Missions...
CSG => Parsing:  Techroom...
CSG => Parsing:  Loadout...
CSG => Parsing:  Scoring...
CSG => Parsing:  RedAlert...
CSG => Parsing:  HUD...
CSG => Parsing:  Variables...
CSG => Parsing:  Settings...
CSG => Parsing:  Controls...
CSG => Parsing:  Cutscenes...
CSG => Parsing:  Last Missions...
CSG => Loading complete!
Got event GS_EVENT_START_GAME (1) in state GS_STATE_SIMULATOR_ROOM (20)
CFILE: Creating new directory '/Users/cliffgordon/Library/Application Support/HardLightProductions/FreeSpaceOpen/data/'
CFILE: Creating new directory '/Users/cliffgordon/Library/Application Support/HardLightProductions/FreeSpaceOpen/data/players/'
PLR => Saving 'chief1983.plr' with version 2...
PLR => Saving:  Flags...
PLR => Saving:  Info...
PLR => Saving:  Scoring...
PLR => Saving:  ScoringMulti...
PLR => Saving:  HUD...
PLR => Saving:  Variables...
PLR => Saving:  Multiplayer...
PLR => Saving:  Controls...
PLR => Saving:  Settings...
PLR => Saving complete!
=================== STARTING LEVEL LOAD ==================
ANI 2_Loading with size 824x43 (32.8% wasted)
ANI 2_Loading.ani with size 824x43 (32.8% wasted)
Starting model page in...
Beginning level bitmap paging...
Loading warp model
 -1
SHOCKWAVE =>  Loading default shockwave animation... 
SHOCKWAVE =>  Default animation load: SUCCEEDED!!
MISSION LOAD: 'massive battle2'
Starting mission message count : 205
Ending mission message count : 205
Current soundtrack set to -1 in event_music_reset_choices
Current soundtrack set to -1 in event_music_set_soundtrack
Loading model 'bonus2t-02.pof' into slot '0'
Submodel 'hercd' is detail level 3 of 'herca'
Submodel 'hercb' is detail level 1 of 'herca'
Submodel 'hercc' is detail level 2 of 'herca'
Submodel 'thruster01b' is detail level 1 of 'thruster01a'
Submodel 'thruster01c' is detail level 2 of 'thruster01a'
Submodel 'thruster02b' is detail level 1 of 'thruster02a'
Submodel 'thruster02c' is detail level 2 of 'thruster02a'
Submodel 'thruster03b' is detail level 1 of 'thruster03a'
Submodel 'thruster03c' is detail level 2 of 'thruster03a'
Submodel 'thruster04b' is detail level 1 of 'thruster04a'
Submodel 'thruster04c' is detail level 2 of 'thruster04a'
Submodel 'thruster05b' is detail level 1 of 'thruster05a'
Submodel 'thruster05c' is detail level 2 of 'thruster05a'
Submodel 'thruster06b' is detail level 1 of 'thruster06a'
Submodel 'thruster06c' is detail level 2 of 'thruster06a'
Submodel 'hercd' is detail level 2 of 'hercb'
Submodel 'hercc' is detail level 1 of 'hercb'
Submodel 'hercd' is detail level 1 of 'hercc'
Loading model 'capital01.pof' into slot '1'
Subsystem 'fighterbay' on ship capital01.pof is not recognized as a common subsystem type
Submodel 'destroyer01d' is detail level 1 of 'destroyer01c'
Submodel 'destroyer01c' is detail level 2 of 'destroyer01a'
Submodel 'destroyer01b' is detail level 1 of 'destroyer01a'
Submodel 'destroyer01d' is detail level 3 of 'destroyer01a'
Submodel 'turret02b' is detail level 1 of 'turret02a'
Submodel 'turret03b' is detail level 1 of 'turret03a'
Submodel 'turret01b' is detail level 1 of 'turret01a'
Submodel 'turret04b' is detail level 1 of 'turret04a'
Submodel 'turret05b' is detail level 1 of 'turret05a'
Submodel 'destroyer01c' is detail level 1 of 'destroyer01b'
Submodel 'destroyer01d' is detail level 2 of 'destroyer01b'
Loading model 'capital2t-01.pof' into slot '2'
Unknown special object type $path45 while reading model capital2t-01.pof
Subsystem 'fighterbay' on ship capital2t-01.pof is not recognized as a common subsystem type
Submodel 'capb' is detail level 1 of 'capa'
Submodel 'capc' is detail level 2 of 'capa'
Submodel 'capd' is detail level 3 of 'capa'
Submodel 'capc' is detail level 1 of 'capb'
Submodel 'capd' is detail level 2 of 'capb'
Submodel 'capd' is detail level 1 of 'capc'
Loading model 'capital2V-01.pof' into slot '3'
Subsystem 'reactor' on ship capital2V-01.pof is not recognized as a common subsystem type
Subsystem 'bridge' on ship capital2V-01.pof is not recognized as a common subsystem type
Subsystem 'fighterbay01' on ship capital2V-01.pof is not recognized as a common subsystem type
Subsystem 'fighterbay02' on ship capital2V-01.pof is not recognized as a common subsystem type
Submodel 'capital2v-01b' is detail level 1 of 'capital2v-01a'
Submodel 'capital2v-01c' is detail level 2 of 'capital2v-01a'
Submodel 'capital2v-01d' is detail level 3 of 'capital2v-01a'
Submodel 'capital2v-01c' is detail level 1 of 'capital2v-01b'
Submodel 'capital2v-01d' is detail level 2 of 'capital2v-01b'
Submodel 'capital2v-01d' is detail level 1 of 'capital2v-01c'
Loading model 'capital2s-01.pof' into slot '4'
Subsystem 'fighterbay01' on ship capital2s-01.pof is not recognized as a common subsystem type
Subsystem 'fighterbay02' on ship capital2s-01.pof is not recognized as a common subsystem type
Submodel 'scapb' is detail level 1 of 'scapa'
Submodel 'scapc' is detail level 2 of 'scapa'
Submodel 'scapd' is detail level 3 of 'scapa'
Submodel 'scapc' is detail level 1 of 'scapb'
Submodel 'scapd' is detail level 2 of 'scapb'
Submodel 'scapd' is detail level 1 of 'scapc'
Loading model 'capital04.pof' into slot '5'
Subsystem 'fighterbay 1' on ship capital04.pof is not recognized as a common subsystem type
Subsystem 'fighterbay 2' on ship capital04.pof is not recognized as a common subsystem type
Submodel 'capital04b' is detail level 1 of 'capital04a'
Submodel 'capital04c' is detail level 2 of 'capital04a'
Submodel 'capital04d' is detail level 3 of 'capital04a'
Submodel 'turret03b-base' is detail level 1 of 'turret03a-base'
Submodel 'turret07b-base' is detail level 1 of 'turret07a-base'
Submodel 'capital04c' is detail level 1 of 'capital04b'
Submodel 'capital04d' is detail level 2 of 'capital04b'
Submodel 'capital04d' is detail level 1 of 'capital04c'
Loading model 'fighter2t-04.pof' into slot '6'
Submodel 'hercb' is detail level 1 of 'herca'
Submodel 'hercc' is detail level 2 of 'herca'
Submodel 'hercd' is detail level 3 of 'herca'
Submodel 'thruster01b' is detail level 1 of 'thruster01a'
Submodel 'thruster01c' is detail level 2 of 'thruster01a'
Submodel 'thruster02b' is detail level 1 of 'thruster02a'
Submodel 'thruster02c' is detail level 2 of 'thruster02a'
Submodel 'hercc' is detail level 1 of 'hercb'
Submodel 'hercd' is detail level 2 of 'hercb'
Submodel 'hercd' is detail level 1 of 'hercc'
Loading model 'fighter2t-05.pof' into slot '7'
Submodel 'fighter2t-05b' is detail level 1 of 'fighter2t-05a'
Submodel 'fighter2t-05c' is detail level 2 of 'fighter2t-05a'
Submodel 'fighter2t-05d' is detail level 3 of 'fighter2t-05a'
Submodel 'thruster04b' is detail level 1 of 'thruster04a'
Submodel 'thruster04c' is detail level 2 of 'thruster04a'
Submodel 'thruster02b' is detail level 1 of 'thruster02a'
Submodel 'thruster02c' is detail level 2 of 'thruster02a'
Submodel 'thruster01b' is detail level 1 of 'thruster01a'
Submodel 'thruster01c' is detail level 2 of 'thruster01a'
Submodel 'thruster03b' is detail level 1 of 'thruster03a'
Submodel 'thruster03c' is detail level 2 of 'thruster03a'
Submodel 'fighter2t-05c' is detail level 1 of 'fighter2t-05b'
Submodel 'fighter2t-05d' is detail level 2 of 'fighter2t-05b'
Submodel 'fighter2t-05d' is detail level 1 of 'fighter2t-05c'
Loading model 'bomber09.pof' into slot '8'
Submodel 'bomber09b-hull' is detail level 1 of 'bomber09a-hull'
Submodel 'bomber09c-hull' is detail level 2 of 'bomber09a-hull'
Submodel 'bomber09d-hull' is detail level 3 of 'bomber09a-hull'
Submodel 'thruster01b' is detail level 1 of 'thruster01a'
Submodel 'thruster01c' is detail level 2 of 'thruster01a'
Submodel 'thruster02b' is detail level 1 of 'thruster02a'
Submodel 'thruster02c' is detail level 2 of 'thruster02a'
Submodel 'bomber09c-hull' is detail level 1 of 'bomber09b-hull'
Submodel 'bomber09d-hull' is detail level 2 of 'bomber09b-hull'
Submodel 'bomber09d-hull' is detail level 1 of 'bomber09c-hull'
Loading model 'fighter2s-02.pof' into slot '9'
Submodel 'fighterb' is detail level 1 of 'fightera'
Submodel 'fighterc' is detail level 2 of 'fightera'
Submodel 'fighterd' is detail level 3 of 'fightera'
Submodel 'thruster01b' is detail level 1 of 'thruster01a'
Submodel 'thruster01c' is detail level 2 of 'thruster01a'
Submodel 'thruster02b' is detail level 1 of 'thruster02a'
Submodel 'thruster02c' is detail level 2 of 'thruster02a'
Submodel 'fighterc' is detail level 1 of 'fighterb'
Submodel 'fighterd' is detail level 2 of 'fighterb'
Submodel 'fighterd' is detail level 1 of 'fighterc'
Loading model 'fighter11.pof' into slot '10'
Submodel 'shiver11b-hull' is detail level 1 of 'shiver11a-hull'
Submodel 'shiver11c-hull' is detail level 2 of 'shiver11a-hull'
Submodel 'shiver11d-hull' is detail level 3 of 'shiver11a-hull'
Submodel 'thruster01b' is detail level 1 of 'thruster01a'
Submodel 'thruster01c' is detail level 2 of 'thruster01a'
Submodel 'shiver11c-hull' is detail level 1 of 'shiver11b-hull'
Submodel 'shiver11d-hull' is detail level 2 of 'shiver11b-hull'
Submodel 'shiver11d-hull' is detail level 1 of 'shiver11c-hull'
Loading model 'fighter03.pof' into slot '11'
Submodel 'fighter03b-hull' is detail level 1 of 'fighter03a-hull'
Submodel 'fighter03c-hull' is detail level 2 of 'fighter03a-hull'
Submodel 'fighter03d-hull' is detail level 3 of 'fighter03a-hull'
Submodel 'thruster01b' is detail level 1 of 'thruster01a'
Submodel 'thruster01c' is detail level 2 of 'thruster01a'
Submodel 'thruster02b' is detail level 1 of 'thruster02a'
Submodel 'thruster02c' is detail level 2 of 'thruster02a'
Submodel 'fighter03c-hull' is detail level 1 of 'fighter03b-hull'
Submodel 'fighter03d-hull' is detail level 2 of 'fighter03b-hull'
Submodel 'fighter03d-hull' is detail level 1 of 'fighter03c-hull'
Loading model 'bomber2s-02.pof' into slot '12'
Submodel 'hullb' is detail level 1 of 'hulla'
Submodel 'hulld' is detail level 3 of 'hulla'
Submodel 'hullc' is detail level 2 of 'hulla'
Submodel 'hulld' is detail level 2 of 'hullb'
Submodel 'hullc' is detail level 1 of 'hullb'
Submodel 'hulld' is detail level 1 of 'hullc'
Allocating space for at least 38 new ship subsystems ...  a total of 200 is now available (38 in-use).
Allocating space for at least 40 new ship subsystems ...  a total of 400 is now available (210 in-use).
Allocating space for at least 5 new ship subsystems ...  a total of 600 is now available (400 in-use).
Adding default sun.
=================== STARTING LEVEL DATA LOAD ==================
```

**Comment by asarium** [comment]
I cannot reproduce this on Linux even with AddressSanitizer. Can you produce a stacktrace from a debug build? The current stacktrace isn't very useful.

**Comment by chief1983** [comment]
Odd.  The debug build I ran earlier that I built, looked a lot like that one.  Just tried to generate it again, and now I get completely different stacks.  Finally got a stack that was about as long as the first one I reported.

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_malloc.dylib        	0x00007fffc7e42e0e small_free_list_remove_ptr + 144
1   libsystem_malloc.dylib        	0x00007fffc7e429be small_malloc_from_free_list + 394
2   libsystem_malloc.dylib        	0x00007fffc7e40a03 szone_malloc_should_clear + 1649
3   libsystem_malloc.dylib        	0x00007fffc7e44066 malloc_zone_memalign + 156
4   libsystem_malloc.dylib        	0x00007fffc7e45bf2 posix_memalign + 25
5   libavutil.55.30.100.dylib     	0x0000000108fae1aa av_mallocz + 58
```

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libavcodec.57.57.101.dylib    	0x000000010c3617a0 avpriv_codec_get_cap_skip_frame_fill_param + 0
1   libavformat.57.50.100.dylib   	0x000000010cff0712 0x10cf46000 + 698130
```

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libavformat.57.50.100.dylib   	0x000000010c9c8384 0x10c924000 + 672644
```

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_malloc.dylib        	0x00007fffc7e41f3f free + 186
1   libavutil.55.30.100.dylib     	0x00000001078f160d av_buffer_unref + 61
2   fs2_open_3_7_5_x64-DEBUG      	0x00000001050f4e61 ffmpeg::WaveFile::Open(char const*, bool) + 4865
3   fs2_open_3_7_5_x64-DEBUG      	0x00000001050fd579 snd_load(game_snd*, int) + 1417
4   fs2_open_3_7_5_x64-DEBUG      	0x0000000104a1f578 gamesnd_load_gameplay_sounds() + 616
5   fs2_open_3_7_5_x64-DEBUG      	0x00000001048cc433 freespace_mission_load_stuff() + 131
6   fs2_open_3_7_5_x64-DEBUG      	0x00000001048cc568 game_post_level_init() + 184
7   fs2_open_3_7_5_x64-DEBUG      	0x00000001048cc975 game_start_mission() + 437
8   fs2_open_3_7_5_x64-DEBUG      	0x00000001048da9db game_enter_state(int, int) + 683
9   fs2_open_3_7_5_x64-DEBUG      	0x0000000104a19919 gameseq_set_state(int, int) + 377
10  fs2_open_3_7_5_x64-DEBUG      	0x00000001048d92be game_process_event(int, int) + 286
11  fs2_open_3_7_5_x64-DEBUG      	0x0000000104a19dd5 gameseq_process_events() + 165
12  fs2_open_3_7_5_x64-DEBUG      	0x00000001048dcd19 game_main(int, char**) + 473
13  fs2_open_3_7_5_x64-DEBUG      	0x00000001048de5aa actual_main(int, char**) + 522
14  fs2_open_3_7_5_x64-DEBUG      	0x00000001048de7f2 main + 34
15  libdyld.dylib                 	0x00007fffc7cbe255 start + 1
```

**Comment by asarium** [comment]
Have you tried rebuilding the FFmpeg libraries from an official source tarball (e.g. 3.1)? The linux libraries use 3.1.3 and if you used the git version then there may have been a bug that was fixed since then.

**Comment by chief1983** [comment]
Still crashes on load, with 3.1.5, everything built on the same machine.

**Comment by chief1983** [comment]
```
Application Specific Information:
abort() called
*** error for object 0x7fbdafd2e000: incorrect checksum for freed object - object was probably modified after being freed.
 

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fffc7decdda __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fffc7ed8787 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fffc7d52420 abort + 129
3   libsystem_malloc.dylib        	0x00007fffc7e4cfb1 szone_error + 626
4   libsystem_malloc.dylib        	0x00007fffc7e4e979 small_free_list_remove_ptr_no_clear + 766
5   libsystem_malloc.dylib        	0x00007fffc7e428d3 small_malloc_from_free_list + 159
6   libsystem_malloc.dylib        	0x00007fffc7e40a03 szone_malloc_should_clear + 1649
7   libsystem_malloc.dylib        	0x00007fffc7e44066 malloc_zone_memalign + 156
8   libsystem_malloc.dylib        	0x00007fffc7e45bf2 posix_memalign + 25
9   libavutil.55.28.100.dylib     	0x000000010736ac39 av_malloc + 57
10  fs2_open_3_7_5_x64-DEBUG      	0x0000000104b5e579 snd_load(game_snd*, int) + 1417
11  fs2_open_3_7_5_x64-DEBUG      	0x0000000104480578 gamesnd_load_gameplay_sounds() + 616
12  fs2_open_3_7_5_x64-DEBUG      	0x000000010432d433 freespace_mission_load_stuff() + 131
13  fs2_open_3_7_5_x64-DEBUG      	0x000000010432d568 game_post_level_init() + 184
14  fs2_open_3_7_5_x64-DEBUG      	0x000000010432d975 game_start_mission() + 437
15  fs2_open_3_7_5_x64-DEBUG      	0x000000010433b9db game_enter_state(int, int) + 683
16  fs2_open_3_7_5_x64-DEBUG      	0x000000010447a919 gameseq_set_state(int, int) + 377
17  fs2_open_3_7_5_x64-DEBUG      	0x000000010433a2be game_process_event(int, int) + 286
18  fs2_open_3_7_5_x64-DEBUG      	0x000000010447add5 gameseq_process_events() + 165
19  fs2_open_3_7_5_x64-DEBUG      	0x000000010433dd19 game_main(int, char**) + 473
20  fs2_open_3_7_5_x64-DEBUG      	0x000000010433f5aa actual_main(int, char**) + 522
21  fs2_open_3_7_5_x64-DEBUG      	0x000000010433f7f2 main + 34
22  libdyld.dylib                 	0x00007fffc7cbe255 start + 1
```

**Comment by chief1983** [comment]
```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0xfffffca1a635c208
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0xfffffca1a635c208:
--> shared memory          00007fffffffc000-00007fffffffd000 [    4K] r-x/r-x SM=SHM  
    

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_malloc.dylib        	0x00007fffc7e422b9 szone_size + 546
1   libavutil.55.28.100.dylib     	0x000000010f9c52cd av_buffer_unref + 61
2   fs2_open_3_7_5_x64-DEBUG      	0x000000010d1c6e61 ffmpeg::WaveFile::Open(char const*, bool) + 4865
3   fs2_open_3_7_5_x64-DEBUG      	0x000000010d1cf579 snd_load(game_snd*, int) + 1417
4   fs2_open_3_7_5_x64-DEBUG      	0x000000010caf1578 gamesnd_load_gameplay_sounds() + 616
5   fs2_open_3_7_5_x64-DEBUG      	0x000000010c99e433 freespace_mission_load_stuff() + 131
6   fs2_open_3_7_5_x64-DEBUG      	0x000000010c99e568 game_post_level_init() + 184
7   fs2_open_3_7_5_x64-DEBUG      	0x000000010c99e975 game_start_mission() + 437
8   fs2_open_3_7_5_x64-DEBUG      	0x000000010c9ac9db game_enter_state(int, int) + 683
9   fs2_open_3_7_5_x64-DEBUG      	0x000000010caeb919 gameseq_set_state(int, int) + 377
10  fs2_open_3_7_5_x64-DEBUG      	0x000000010c9ab2be game_process_event(int, int) + 286
11  fs2_open_3_7_5_x64-DEBUG      	0x000000010caebdd5 gameseq_process_events() + 165
12  fs2_open_3_7_5_x64-DEBUG      	0x000000010c9aed19 game_main(int, char**) + 473
13  fs2_open_3_7_5_x64-DEBUG      	0x000000010c9b05aa actual_main(int, char**) + 522
14  fs2_open_3_7_5_x64-DEBUG      	0x000000010c9b07f2 main + 34
15  libdyld.dylib                 	0x00007fffc7cbe255 start + 1
```

**Comment by chief1983** [comment]
Have found that on this mission the crash is always after starting to load beep_1.wav.  Using retail data.

**Comment by chief1983** [comment]
Still an issue with both the latest nightly and a locally built build.

**Comment by chief1983** [comment]
Got my hands on Maja again, and decided to extract the beep_5.wav that had loaded, and put it in a data folder named as beep_1.wav.  As I hoped, the loading got past beep_1.wav now.  But then it crashed on l_alien2.wav.  So I did the same thing, with l_alien1.wav.  Got past that.  Then I got another crash.  This time, after loading Turret_V1.wav, I actually have an Assertion in the log, and not just a crash with no information other than a bizarre stack trace.

```
SOUND ==> Loading 'Turret_V1.wav'
ASSERTION: "tmp_offset==cb->raw_position" at cfilearchive.cpp:226

Assert: "tmp_offset==cb->raw_position"
File: cfilearchive.cpp
Line: 226

  1   fs2_open_3_7_5_20170125_f376142_x64-FASTDBG 0x00000001094b28da _ZN2os7dialogs13AssertMessageEPKcS2_iS2_z + 890
  2   fs2_open_3_7_5_20170125_f376142_x64-FASTDBG 0x00000001091d2cec _Z6cfreadPviiP5CFILE + 284
  3   fs2_open_3_7_5_20170125_f376142_x64-FASTDBG 0x0000000109337ce7 _ZN12_GLOBAL__N_19cfileReadEPvPhi + 23
  4   libavformat.57.50.100.dylib         0x000000010bbd0ef3 avio_seek + 1171

[ This info is in the clipboard so you can paste it somewhere now ]


Use Debug to break into Debugger, Exit will close the application.
```

Then I realized it's not the file itself that is messed up, it's reading it from the VP that is crashing.  As I had replaced Turret_V1 with Turret_V2, and it got past V1 but still crashed loading V2 from the VP.  I then just put V2 in the data folder, not renaming it, and it got past V2 that time.  Then it crashed with an Assertion in the log again.

```
SOUND ==> Loading 'beam_shot1.wav'
ASSERTION: "tmp_offset==cb->raw_position" at cfilearchive.cpp:226

Assert: "tmp_offset==cb->raw_position"
File: cfilearchive.cpp
Line: 226

  1   fs2_open_3_7_5_20170125_f376142_x64-FASTDBG 0x000000010961e8da _ZN2os7dialogs13AssertMessageEPKcS2_iS2_z + 890
  2   fs2_open_3_7_5_20170125_f376142_x64-FASTDBG 0x000000010933ecec _Z6cfreadPviiP5CFILE + 284
  3   fs2_open_3_7_5_20170125_f376142_x64-FASTDBG 0x00000001094a3ce7 _ZN12_GLOBAL__N_19cfileReadEPvPhi + 23
  4   libavformat.57.50.100.dylib         0x000000010bd37ef3 avio_seek + 1171

[ This info is in the clipboard so you can paste it somewhere now ]


Use Debug to break into Debugger, Exit will close the application.
```

Continued replacing sounds for beam_shot1.wav, and BT_SGreen.wav, and I have been able to launch a new build into a mission for the first time in age.  Every one of these files being read from the VP leads to a 100% reproducible crash to desktop on my system, using nightlies or my own builds, debug, fast debug, or release.  I only saw two of them ever put the assertion in the log.  The first only did it once, on subsequent runs, it just died after the loading line.  The second one put the Assertion in the log more than once.  Still not sure if this helps but I still suspect there is something wrong with either our cfile code that reads from VPs, and how we use it with libavcodec, or with the Mac libavcodec bundle we are providing (that I built :P )

**Comment by asarium** [comment]
That's great! That narrows it down to how FFmpeg reads the data from our file system and it also means that it has something to do with the seeking function (since all your stacktraces show that the assertion happens from `avio_seek`).

**Comment by chief1983** [comment]
Yeah I was hoping that might narrow it down some, first real concrete dumps of the crash I've been able to generate.  I don't know if the fact that it happens in a specific subset of files, and only those files, in the sparky vp.  I don't know if it's how they're aligned, or what the issue is.

**Comment by asarium** [comment]
This is definitely helpful for tracking it down. It's weird since the bug only happens on Mac which suggests that it's caused by something special in the mac libraries but that's just speculation at this point.

**Comment by chief1983** [comment]
The libraries that exist now were built on an older Macbook, with an earlier SDK than the applications I am building now (not sure what SDK the nightly process is using).  I have tried to rebuild the library and use it but had trouble correctly shoe-horning it into the build system.  Need to give that another go to see if it helps, but if we are that bound to SDK matching, it doesn't make the library very portable, so it wouldn't really be a solution for a build system that should work on any other dev's platform which could be using any of several versions of OS X and Xcode, and the SDK.

**Comment by asarium** [comment]
The assertion happens in our code so hopefully it's not an issue with the SDK version. I have checked the source of `avio_seek` and there are no direct calls to our read function there but it may be hidden somewhere. Did you have any luck with adding the right compiler options for enabling debugging? It would be very helpful to have a full stack trace with actual parameter or variable values.

**Comment by chief1983** [comment]
Not yet, I mean I did try our 'debug' configuration but nothing was in any better shape for debugging than before.  Could use a mac developer with more experience with that stuff, even enabling after generation would be helpful but figuring out how to get CMake to do that for us would be ideal.

**Comment by pisaacson** [comment]
I get this error also see the log below. Let me know if there is anything additional I can provide.

I build with a pure cmake build through a local macports portfile. 

If I have preload mission sounds enabled, a mission will crash on load, otherwise it has to be triggered from an in-mission event. Pressing the 'c' key to communicate will always trigger the crash. Disabling all sound prevents the crash, but obviously makes playing less than enjoyable.

[fs2_open.txt](https://github.com/scp-fs2open/fs2open.github.com/files/753473/fs2_open.txt)

**Comment by pisaacson** [comment]
Here is the OS X crash log excerpt:

Process:               fs2_open_3_7_5_x64-DEBUG [9754]
Path:                  /Applications/MacPorts/*/fs2_open_3_7_5_x64-DEBUG.app/Contents/MacOS/fs2_open_3_7_5_x64-DEBUG
Identifier:            fs2_open_3_7_5_x64-DEBUG
Version:               FreeSpace 2 Open version 3.7.5 (???)
Code Type:             X86-64 (Native)
Parent Process:        wxlauncher [9706]
Responsible:           fs2_open_3_7_5_x64-DEBUG [9754]
User ID:               502

Date/Time:             2017-02-05 19:08:23.247 -0600
OS Version:            Mac OS X 10.11.6 (15G1217)
Report Version:        11
Anonymous UUID:        2DF16E34-7282-5ACD-7798-6D0A163B172D

Sleep/Wake UUID:       59F687CB-0361-40DD-ACBF-4DB50F4DFE42

Time Awake Since Boot: 6700 seconds
Time Since Wake:       850 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
*** error for object 0x7f8e553eca08: incorrect checksum for freed object - object was probably modified after being freed.
 

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff89d2bf06 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff871304ec pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff856196df abort + 129
3   libsystem_malloc.dylib        	0x00007fff82889396 szone_error + 626
4   libsystem_malloc.dylib        	0x00007fff8287eda6 small_malloc_from_free_list + 258
5   libsystem_malloc.dylib        	0x00007fff8287bb64 szone_malloc_should_clear + 1411
6   libsystem_malloc.dylib        	0x00007fff8287b5a1 malloc_zone_malloc + 71
7   libsystem_malloc.dylib        	0x00007fff8287a0cc malloc + 42
8   libc++.1.dylib                	0x00007fff958887de operator new(unsigned long) + 30
9   libc++.1.dylib                	0x00007fff9588c299 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__grow_by(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long) + 139
10  libc++.1.dylib                	0x00007fff9588bf62 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::push_back(char) + 86
11  fs2_open_3_7_5_x64-DEBUG      	0x0000000102058e99 std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::overflow(int) + 121
12  fs2_open_3_7_5_x64-DEBUG      	0x0000000102054030 std::__1::basic_streambuf<char, std::__1::char_traits<char> >::xsputn(char const*, long) + 112
13  fs2_open_3_7_5_x64-DEBUG      	0x0000000101dba231 std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char) + 241
14  fs2_open_3_7_5_x64-DEBUG      	0x00000001020069ba std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) + 222
15  fs2_open_3_7_5_x64-DEBUG      	0x00000001020043b5 os::dialogs::Error(char const*) + 518
16  fs2_open_3_7_5_x64-DEBUG      	0x0000000102003ac5 os::dialogs::AssertMessage(char const*, char const*, int, char const*, ...) + 1301
17  fs2_open_3_7_5_x64-DEBUG      	0x0000000101dc0213 cfread(void*, int, int, CFILE*) + 300
18  fs2_open_3_7_5_x64-DEBUG      	0x0000000101ed4259 (anonymous namespace)::cfileRead(void*, unsigned char*, int) + 23
19  libavformat.57.dylib          	0x0000000104d31633 0x104d05000 + 181811

**Comment by chief1983** [comment]
Interesting comment about load all mission sounds, I always play with that enabled and didn't think to suggest using it to reproduce.  The comm menu is probably using the beep sound I first noticed was crashing.  That may help someone with investigating the root cause of the crash.  If you get a vp extractor and extract the identified files into the filesystem it will circumvent the crashes, as it seems to be cfile/vp/libav related.  Taking the vp files out of the equation avoids it.

**Comment by jg18** [comment]
This may help indirectly: I'm working with m!m on getting CMake to configure the generated Xcode project to generate debug symbols but we don't yet have it working. In the meantime, you can configure the project manually: open the Xcode project's build settings and for the FS2_Open project and the code and Freespace2 targets, set GEnerate Debug Symbols to Yes and set StripDebug Symbols on Copy to No and Strip Linked Product to No. The generated FSO app should then have debug symbols, making it possible to use Xcode's debugging tools or if you prefer LLDB (Apple's GDB), see the lower-right corner of the Xcode debug window (synonymous with what Xcode calls Console I think). You can get to the project's build settings by going to Project Navigator (the left sidebar pane showing the project's files), clicking on FS2_Open (top of the tree) and the main window should have an option to view the Build Settings. You can type "symbols" into the filter box. You may also want to uncheck "Always Show Disassembly"from the top menu Debug >> Debug Workflow submenu.  Hope that helps.

**Comment by chief1983** [comment]
i have been pouring over the list trying to find those settings that will magically fix debugging symbols.  Can you attach screenshots of the relevant ones changed, or which category the generate debug symbols one is under?  I had found that we aren't defining the debug symbol type to dwarf or dwarf with dsym.  Don't we need to define that one too?

**Comment by jg18** [comment]
Screenshot: <img width="1512" alt="xcode_symbols_settings" src="https://cloud.githubusercontent.com/assets/6183333/22858298/efea5ff2-f06d-11e6-81bf-51cf52aca63a.png">

Yeah we should probably define the debug symbol type as well. I'm guessing it defaults to DWARF (i.e., without  dSYM) since it currently doesn't generate a  dSYM, in which case it must embed the debug symbols in the FSO app bundle somehow, haven't looked into exactly where.

**Comment by jg18** [comment]
Actually, for Debug and Fast Debug builds,  do we prefer dSYM over embedding the debug symbols into the FSO app bundle? Personally I like embedding, one less file that people have to copy into their FS2/TC folder. I think things work the same either way, not 100% sure though.

**Comment by chief1983** [comment]
Dwarf should put them in the binary itself, inside the app bundle.  I think I read something about dsym working better than embedded symbols but I would have to find that reference.

**Comment by chief1983** [comment]
Ok, so generate debug symbols was actually already Yes by default on LLVM 8.0, in the debug build.  So the other options, not stripping symbols and symbol file type, I had already tried enabling.  I'll give it another go but I don't think it's been enough for me to get a useful stack trace.

**Comment by chief1983** [comment]
Grr, FS2_Open project had Generate Debug Symbols set to Yes, but the Freespace2 target specifically had it overridden to No.  I think I got this, I cleared the value being set on any of the subprojects, and set it on Debug for the FS2 Open project.  It will now apply from that setting to all the children.  Let's see if that helps.

**Comment by asarium** [comment]
@jg18 has a patch that should set those properties properly so once that it merged you won't have to mess with the project files manually.

**Comment by chief1983** [comment]
http://stackoverflow.com/questions/4850788/prevent-compiling-from-generating-dsym-on-os-x-using-make

`However, note that with Apple's toolchain, the DWARF resides in the .o files, and does not get linked into the final binary. (GDB knows how to find it, but it needs the .o files laying around on disk.) If you intend to send the binaries to someone else, you really do need to produce a dSYM to send them along with the binary.`

http://stackoverflow.com/questions/35224247/cmake-g-flag-not-generating-dwarf-with-dsym-file-debug-information

Dang, and here I was trying to see if I could still be helpful in finding what needed to be enabled.  If you guys have made all the necessary progress though I can just wait for the PR to see if I can get a stack trace from this crash then.

**Comment by chief1983** [comment]
<img width="1687" alt="screen shot 2017-02-14 at 9 59 23 am" src="https://cloud.githubusercontent.com/assets/145825/22936835/4b40d04a-f29c-11e6-90d7-b4f8c7ef7350.png">

Seems I'm in better shape than I was, I didn't get dropped to assembly on the crash.  Maybe we can figure this out after all?

**Comment by jg18** [comment]
I have createdpull request #1231  for configuring Xcode projects to generate debug symbols on Debug builds. Special thanks to m!m for his help with figuring out how to configure CMake.

I just noticed the other comments on this issue. Should I addd a follow up commit to generate a .dSYM file as well?

**Comment by jg18** [comment]
PR has been updated to generate .dSYM file. Thanks @chief1983 for doing the research and finding out that we do need the .dSYM.

**Comment by chief1983** [comment]
Ok, I think that also compiling ffmpeg with debugging enabled might have helped get us what we need.  My Thread 1 stack goes much deeper in the debugger now.  But when I detach and get a stack trace it doesn't actually look the same as the stack trace I was seeing in the debugger.

```
Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_platform.dylib      	0x00007fffcebaebc1 _simple_salloc + 48
1   libsystem_platform.dylib      	0x00007fffcebaeb59 _simple_asl_msg_new + 11
2   libsystem_platform.dylib      	0x00007fffcebaf9b3 _simple_asl_log_prog + 31
3   libsystem_malloc.dylib        	0x00007fffceb31213 _malloc_vprintf + 169
4   libsystem_malloc.dylib        	0x00007fffceb30cff malloc_printf + 159
5   libsystem_malloc.dylib        	0x00007fffceb2de4d szone_error + 354
6   libsystem_malloc.dylib        	0x00007fffceb22bec tiny_malloc_from_free_list + 1148
7   libsystem_malloc.dylib        	0x00007fffceb21472 szone_malloc_should_clear + 400
8   libsystem_malloc.dylib        	0x00007fffceb24fb6 malloc_zone_memalign + 156
9   libsystem_malloc.dylib        	0x00007fffceb26b42 posix_memalign + 25
10  libavutil.55.34.101.dylib     	0x000000010eee08d8 av_malloc + 88 (mem.c:97)
11  libavutil.55.34.101.dylib     	0x000000010eee0cc5 av_mallocz + 21 (mem.c:254)
12  libavutil.55.34.101.dylib     	0x000000010eed54b4 av_frame_alloc + 20 (frame.c:147)
13  libavformat.57.56.101.dylib   	0x000000010ee00b01 try_decode_frame + 65 (utils.c:2925)
14  libavformat.57.56.101.dylib   	0x000000010edff6bb avformat_find_stream_info + 7819 (utils.c:3727)
15  fs2_open_3_7_5_x64-DEBUG      	0x000000010bb858f1 libs::ffmpeg::FFmpegContext::createContext(CFILE*) + 3665 (FFmpegContext.cpp:126)
16  fs2_open_3_7_5_x64-DEBUG      	0x000000010c072704 ffmpeg::WaveFile::Open(char const*, bool) + 1876 (WaveFile.cpp:186)
17  fs2_open_3_7_5_x64-DEBUG      	0x000000010c07b999 snd_load(game_snd*, int) + 1417 (sound.cpp:321)
18  fs2_open_3_7_5_x64-DEBUG      	0x000000010b9770a8 gamesnd_load_gameplay_sounds() + 616 (gamesnd.cpp:539)
19  fs2_open_3_7_5_x64-DEBUG      	0x000000010b81d963 freespace_mission_load_stuff() + 131 (freespace.cpp:1280)
20  fs2_open_3_7_5_x64-DEBUG      	0x000000010b81da93 game_post_level_init() + 179 (freespace.cpp:1350)
21  fs2_open_3_7_5_x64-DEBUG      	0x000000010b81dd75 game_start_mission() + 437 (freespace.cpp:1417)
22  fs2_open_3_7_5_x64-DEBUG      	0x000000010b82c44b game_enter_state(int, int) + 683 (freespace.cpp:5638)
23  fs2_open_3_7_5_x64-DEBUG      	0x000000010b971449 gameseq_set_state(int, int) + 377 (gamesequence.cpp:279)
24  fs2_open_3_7_5_x64-DEBUG      	0x000000010b82ad0e game_process_event(int, int) + 286 (freespace.cpp:4797)
25  fs2_open_3_7_5_x64-DEBUG      	0x000000010b971905 gameseq_process_events() + 165 (gamesequence.cpp:393)
26  fs2_open_3_7_5_x64-DEBUG      	0x000000010b82e7e9 game_main(int, char**) + 473 (freespace.cpp:6730)
27  fs2_open_3_7_5_x64-DEBUG      	0x000000010b830010 actual_main(int, char**) + 560 (freespace.cpp:7919)
28  fs2_open_3_7_5_x64-DEBUG      	0x000000010b830262 main + 34 (freespace.cpp:7964)
29  libdyld.dylib                 	0x00007fffce99f235 start + 1
```

<img width="1727" alt="screen shot 2017-03-28 at 3 18 44 pm" src="https://cloud.githubusercontent.com/assets/145825/24425435/e28aeb68-13c9-11e7-9fe8-f5052479182c.png">

**Comment by asarium** [comment]
That value "18446744073709534703" looks suspiciously like an overflow or an invalid cast. Maybe the file is not well formed and our code can't handle that for some reason. I'll step through the loading code on my machine, maybe I can reproduce that value.

**Comment by asarium** [comment]
I can reproduce the invalid value!!!!

**Comment by asarium** [comment]
@chief1983 I think I fixed the crash issue, please test the changes of #1325 to confirm that it fixes the crash.
