### ISSUE TITLE
Targeting brackets in top left corner of screen after a few turns

### ISSUE THREAD

**Issue by Mr-Maniac** [scp-fs2open/fs2open.github.com#1827]
commit 13076364d609e18bdc53243a31348279620cdf1d (13th August - but occured before, too)
Linux
3840x2160
Tried MediaVPs and retail

After moving around a bit, the targeting bracket will get stuck at upper left corner of screen. The rest of the HUD is OK (arrows point in correct direction etc.).
When looking around with POV-hat of joystick, the targeting brackets are at correct position for a short moment of time (while viewport moves around). When looking forward, again, the target brackets are at the upper left corner of screen, again.
Before:
![screen0029_fhd](https://user-images.githubusercontent.com/25706260/44107910-22bd524a-9ff9-11e8-83ad-be739cddeed5.png)
After:
![screen0039_fhd](https://user-images.githubusercontent.com/25706260/44107918-286c7fc2-9ff9-11e8-8327-eddc26cf8c34.png)
(Screenshots scaled down to 1920x1080)
Maybe related to https://github.com/scp-fs2open/fs2open.github.com/issues/1655?

Just tell me what infos you need.

**Comment by Mr-Maniac** [comment]
Well, I haven't programmed C/C++, yet, but maybe I can try to look into it myself. Any hints about where to start?
I assume somewhere in code/hud (maybe hudtargetbox.cpp or hudbracket.cpp or something like this)?
I'm compiling fs2_open myself anyway, so I could try a few things...

**Comment by Artyrm** [comment]
AFAIK you can create "false" resolution for desktop in Windows and this way game will able to run like it is on hi-res monitor.

**Comment by asarium** [comment]
This bug is very similar to the issue I fixed in #1849. Once that is merged you could check if this bug has also been fixed by those changes.

**Comment by Mr-Maniac** [comment]
Unfortunately, this bug still exist. But now, the sub-system is market in the target window.
Self-compiled today (commit e04f1b4ca480600ea4c95347002bd825b4e1d785 from 18. Sep. 2018 10:08:19 GMT)

**Comment by MageKing17** [comment]
I thought we already had an issue for this, but it turns out I was thinking of [Mantis #3155](http://scp.indiegames.us/mantis/view.php?id=3155).

**Comment by Mithi83** [comment]
Maybe I can shed some light on this issue. I've compiled a recent git version and debugged my way through the code. I'm using the first Diaspora mission for my tests if that's relevant using a resolution of 3840x2160 (4k). At first the error does not occur an the brackets are properly rendered. However at some point the error occurs.

Whats happening is the following: HudGaugeBrackets::renderObjectBrackets calls model_find_2d_bound_min, which in turn calls g3_project_vertex. The assignment of p->screen.xyw.x resp p->screen.xyw.y relies on the values of Canvas_width and Canvas_height. Normally, I'd expect them to be 3840 resp. 2160. They are however 180 resp 135.

Using a data breakpoint on those variables I can see that they are set during game_render_frame -> g3_start_frame_func to the expected values of 3840x2160. However they are overwritten by a callchain of game_render_hud -> hud_render_all -> hud_render_gauges -> HudGaugeTargetBox::render -> HudGaugeTargetBox::renderTargetShip -> HudGaugeTargetBox::renderTargetSetup -> g3_start_frame_func to the unexpected lower values of 180x135.

Since the call to HudGaugeBrackets::renderObjectBrackets happens after HudGaugeTargetBox::renderTargetShip and the Canvas_width/Canvas_height is not reset to proper values (at least in the error case) the error occurs.

My best guess is that HudGaugeTargetBox::render should not modify global state without restoring it upon leaving. How to implement that is however beyond my expertise with this code.

My current hypothesis is that gr_screen.clip_width and gr_screen.clip_height should not be modified without backup. Note that there are several such potentially dangerous constructs in HudGaugeHardpoints::render, HudGaugeTargetBox::renderTargetSetup, and HudGaugeShield::showShields. I'll try out an idea in the next few days, but perhaps someone more familiar with the code will see something more in this analysis.

**Comment by Mithi83** [comment]
For a quick test I tried to save gr_screen.clip_width and gr_screen.clip_height before modifying it in HudGaugeTargetBox::renderTargetSetup and restore it during HudGaugeTargetBox::renderTargetClose. This did not fix the problem.

Then I commented out the four lines around line 503 up to gr_screen.clip_height = clip_height. This seems to help. Considering the comment above these lines someone should put more thought into this as I have no clue if this breaks other functionality or setups.

**Comment by asarium** [comment]
First of all, thank you very much for your investigation of the cause of this issue.

I agree, the code that seems to cause this issue looks like a very crude hack and I'm not surprised that it breaks in unexpected ways. What I'm not sure about is why this doesn't happen always but only after a certain time. `HudGaugeBrackets::render` does call `g3_start_frame` but only if we are not in a frame already. Since it works for some time before breaking, I assume that we are missing a `g3_end_frame` somewhere. Could you check the value of `G3_count` in your tests and see if a change in that correlates to the bug appearing?

**Comment by Mithi83** [comment]
Good guess, I think you're on the right track. The value of G3_count is initially 0 (measured in HudGaugeBrackets::render before g3_start_frame). In that state the bug does not occur. Later, when the bug occurs, the value of G3_count  is 1. I verified with a breakpoint that the g3_start_frame is no longer called in HudGaugeBrackets::render.

**Comment by asarium** [comment]
I looked through all usages if `g3_start_frame` and I could not find any case where the end call could be missing due to an early return. There are a few cases where that is done in an error case but you would see an `Int3` error in that case.

Maybe you could try adding a breakpoint at the end of `game_frame` and see if the value of `G3_count` is wrong globally.

**Comment by Mithi83** [comment]
At a breakpoint in game_frame (line 4267 current git master) G3_count is 0 when the bug does not occur and 1 when it occurs.

**Comment by asarium** [comment]
What you could do now is go to `g3_start_frame_func`, uncomment the two parameters and log those with something like `mprintf(("start_frame: %s:%d\n", filename, lineno));` and do the same in `g3_end_frame_func`.

Then let the game run until the bug occurs and have a look at the log. It should be possible to see which start frame call does not have an end frame call from that data.

**Comment by Mithi83** [comment]
I was wondering why I did not get the debug output until I found out that I did not build for debug but release with debug symbols. Retrying with a full debug build I quickly found that HudGaugeOffscreen::calculatePosition triggered the second Int3(). Adding a !in_frame conditional g3_end_frame() fixes the bug. I did not encounter the first Int3() in this function, but to be safe I suggest to call g3_end_frame there as well.

For completeness here are the values of the relevant variables at the Int3 breakpoint that were involved in getting to this Int3() call in the various if/elseif statements before:
xpos = 898.200317
ypos = 899.999939
gr_screen.clip_right_unscaled = 1600
gr_screen.clip_left_unscaled = 0
gr_screen.clip_top_unscaled = 0
gr_screen.clip_bottom_unscaled = 900
Note that the last comparison of ypos >= gr_screen.clip_bottom_unscaled failed for a minimal amount that might hint at a rounding problem. The ship that caused the bug moved out of sight to the bottom of the screen so it seems plausible that this would have been the case I'd have expected to happen.

**Comment by asarium** [comment]
Yes, a floating point rounding issue seems to be the most likely here. I don't have enough data to say how this could be fixed but for now you could just add the
```
	if(!in_frame)
		g3_end_frame();
```
before both returns and submit a pull request with that which would at least fix this issue.

**Comment by MageKing17** [comment]
conditional could be changed to `>= gr_screen.clip_bottom_unscaled - <some epsilon>`?

**Comment by Mithi83** [comment]
I did some further testing by replacing the second Int3() in HudGaugeOffscreen::calculatePosition  (i.e. in the else case after it is neither top, bottom, left nor right) with a mprintf dumping the relevant variables for the if/else-combinations. I then ran a debug build with a 4k resolution an tested all four cases by focussing a ship in the center of the screen, then moving the ship out of sight for each direction. Only the bottom and right case were triggered in the log file. The relevant values of xpos or ypos are always the same.

In all cases the clip_X_unscaled was (left: 0, top: 0, right: 1600, bottom: 900).
In case the ship moved out of sight to the bottom of the screen ypos was always 899.999939 and thus minimally smaller than 900.
In case the ship moved out of sight to the right of the screen xpos was always 1599.999878 and thus minimally smaller than 1600.

I think that the  `xpos = (xpos<1) ? 0 : xpos;` statement is preventing this bug from triggering on the left side. So your epsilon would by that definition be 1. However this does not apply to the right side. For top and bottom the same is true.
